#Command for generating yaml file
kubectl run nginx --image=nginx --restart=Never --dry-run=client -oyaml > nginx.yaml

# Yaml file format
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
#create
kubectl apply -f nginx.yaml


##############Output the yaml file of the pod you just created
kubectl get po nginx -oyaml > createdpod.yaml


###############Output the yaml file of the pod you just created without the cluster-specific information

kubectl get pod nginx -oyaml --export > file.yaml

###############Get the complete details of the pod you just created

kubectl describe pod nginx 

##############Delete the pod you just created
kubectl delete pod nginx
kubectl delete -f nginx.yaml

#############Delete the pod you just created without any delay (force delete)
kubectl delete po nginx --grace-period=0 --force