#######Scale the deployment from 5 replicas to 20 replicas and verify
kubectl scale deploy webapp --replicas=7
kubectl get po -l app=webapp

#####Get the deployment rollout status
kubectl rollout status deploy webapp

#####Get the replicaset that created with this deployment
kubectl get rs -l app=webapp

#####Get the yaml of the replicaset and pods of this deployment
kubectl get rs -l app=webapp -oyaml
kubectl get po -l app=webapp -oyaml

######Delete the deployment you just created and watch all the pods are also being deleted
kubectl delete deploy webapp
kubectl get po -l app=webapp -w

######Create a deployment of webapp with image nginx:1.17.1 with container port 80 and verify the image version
kubectl create deploy webapp --image=nginx:1.17.1 --dry-run=client -oyaml > nginx-deploy.yaml

####Edit port section
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx:1.17.1
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

####Check image
kubectl describe deploy webapp | grep Image

######Update the deployment with the image version 1.17.4 and verify
kubectl set image deploy webapp nginx=nginx:1.17.4
kubectl describe deploy webapp | grep Image

#####Check the rollout history and make sure everything is ok after the update
kubectl rollout history deploy webapp 
kubectl get deploy webapp --show-labels
kubectl get rs -l app=webapp
kubectl get po -l app=webapp

#####Undo the deployment to the previous version 1.17.1 and verify Image has the previous version
kubectl rollout undo deploy webapp
kubectl describe deploy webapp | grep Image`

######Update the deployment with the image version 1.16.1 and verify the image and also check the rollout history
kubectl set image deploy/webapp nginx=nginx:1.16.1
kubectl describe deploy webapp | grep Image
kubectl rollout history deploy webapp

#####Update the deployment to the Image 1.17.1 and verify everything is ok
kubectl rollout undo deploy webapp --to-revision=3
kubectl describe deploy webapp | grep Image
kubectl rollout status deploy webapp

#####pdate the deployment with the wrong image version 1.100 and verify something is wrong with the deployment
kubectl set image deploy/webapp nginx=nginx:1.100
kubectl rollout status deploy webapp (still pending state)
kubectl get pods (ImagePullErr)

#####Undo the deployment with the previous version and verify everything is Ok
kubectl rollout undo deploy webapp
kubectl rollout status deploy webapp
kubectl get pods

#####Check the history of the specific revision of that deployment
kubectl rollout history deploy webapp --revision=7

#####Pause the rollout of the deployment
kubectl rollout pause deploy webapp

#####Update the deployment with the image version latest and check the history and verify nothing is going on
kubectl set image deploy/webapp nginx=nginx:latest
kubectl rollout history deploy webapp (No new revision)

#####Resume the rollout of the deployment
kubectl rollout resume deploy webapp

#####Check the rollout history and verify it has the new version
ubectl rollout history deploy webapp
kubectl rollout history deploy webapp --revision=9
