#####Create an nginx pod with containerPort 80 and it should only receive traffic 
#####only it checks the endpoint / on port 80 and verify and delete the pod.
kubectl run nginx-readi --image=nginx --restart=Never --port=80 --dry-run=client -oyaml > nginx-readi.yaml

##Edit file
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-readi
  name: nginx-readi
spec:
  containers:
  - image: nginx
    name: nginx-readi
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

###verify
kubectl describe po nginx-readi | grep -i readi

##delete
kubecl delete pod nginx-readi
