#####Create an nginx pod which reads username as the environment variable
kubectl run nginx-secret --image=nginx --dry-run=client -oyaml > nginx-secret.yaml

##edit file

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-secret
  name: nginx-secret
spec:
  containers:
  - image: nginx
    name: nginx-secret
    env:
    - name: USER_NAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: user
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

##vrify
kubectl exec -it nginx-secret -- sh
env #USER_NAME=myuser


#####Create an nginx pod which loads the secret as environment variables
##Edit  file
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-secret
  name: nginx-secret
spec:
  containers:
  - image: nginx
    name: nginx-secret
    envFrom:
    - secretRef:
        name: mysecret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

###verify
kubectl exec -it nginx-secret -- sh
env  ## user=myuser password=password
