#####Create a secret mysecret with values user=myuser and password=mypassword
kubectl create secret generic mysecret --from-literal=user=myuser --from-literal=password=mypassword 

#####List the secrets in all namespaces
kubectl get secret --all-namespaces

#####Output the yaml of the secret created above
kubectl get secret mysecret -oyaml

---
apiVersion: v1
data:
  password: bXlwYXNzd29yZA==
  user: bXl1c2Vy
kind: Secret
metadata:
  creationTimestamp: "2021-06-04T07:35:59Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:password: {}
        f:user: {}
      f:type: {}
    manager: kubectl
    operation: Update
    time: "2021-06-04T07:35:59Z"
  name: mysecret
  namespace: default
  resourceVersion: "307"
  selfLink: /api/v1/namespaces/default/secrets/mysecret
  uid: f14352e9-42f7-4f99-9baa-8c050e346852
type: Opaque